export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function BootcampLayout({ children }) {
  return <main id='about'>{children}</main>;
}
